"""Renders scan results to markdown.

Design decision: page `.md` files are generated output, meant to be
committed and reviewed via `git diff` -- like a lockfile, not hand-edited
element by element (re-running `forge scan` would just overwrite manual
edits there anyway). The one file a human is meant to hand-edit is
`locator-priority.yaml` at the repo root; `forge rank` re-sorts every
already-generated page against it without touching source.

The table format below is deliberately rigid (fixed column order, one
element per `### heading`) so `resolver.py` can parse it back out with a
plain line-based reader instead of a general markdown/AST library.
"""

from __future__ import annotations

from pathlib import Path

from playwright_locators_forge.models import PageResult
from playwright_locators_forge.scanner.locator_types import rank_candidates

GENERATED_BANNER = (
    "<!-- AUTO-GENERATED by playwright-locators-forge. Do not hand-edit; "
    "re-run `forge scan` and adjust `locator-priority.yaml` instead. -->"
)


def _page_output_path(output_dir: Path, page: PageResult) -> Path:
    return (output_dir / page.source_file).with_suffix(".md")


def render_page(page: PageResult, priority: dict[str, int], previous_hashes: dict[str, str] | None = None) -> str:
    previous_hashes = previous_hashes or {}
    lines: list[str] = [
        GENERATED_BANNER,
        "",
        f"# {page.source_file}",
        "",
        f"- Framework: {page.framework}",
        f"- Route hint: {page.route_hint}",
        f"- Elements: {len(page.elements)}",
        "",
        "---",
        "",
    ]

    for element in page.elements:
        stale = (
            element.name in previous_hashes
            and previous_hashes[element.name] != element.content_hash
        )
        lines.append(f"### {element.name}")
        lines.append(f"- source: {element.file}:{element.line}")
        lines.append(f"- tag: `{element.tag}`")
        lines.append(f"- hash: {element.content_hash}")
        if stale:
            lines.append(
                f"- ⚠️ stale: source changed since last scan "
                f"(previous hash `{previous_hashes[element.name]}`) — re-run `forge scan`"
            )
        lines.append("")
        lines.append("| rank | type | locator | dynamic | note |")
        lines.append("|---|---|---|---|---|")
        for rank, candidate in rank_candidates(element.candidates, priority):
            dynamic = "yes" if candidate.dynamic else "no"
            note = candidate.note.replace("|", "/") if candidate.note else ""
            value = candidate.value.replace("|", "\\|")
            lines.append(f"| {rank} | {candidate.type} | `{value}` | {dynamic} | {note} |")
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def render_index(pages: list[PageResult]) -> str:
    lines = [
        GENERATED_BANNER,
        "",
        "# Locator Map Index",
        "",
        "| Source file | Route hint | Framework | Elements | Locators file |",
        "|---|---|---|---|---|",
    ]
    for page in sorted(pages, key=lambda p: p.source_file):
        md_path = Path(page.source_file).with_suffix(".md").as_posix()
        lines.append(
            f"| {page.source_file} | {page.route_hint} | {page.framework} | "
            f"{len(page.elements)} | [{md_path}]({md_path}) |"
        )
    return "\n".join(lines).rstrip() + "\n"


def write_pages(output_dir: Path, pages: list[PageResult], priority: dict[str, int]) -> list[Path]:
    from playwright_locators_forge.resolver import parse_page_hashes  # avoid circular import at module load

    written: list[Path] = []
    output_dir.mkdir(parents=True, exist_ok=True)

    for page in pages:
        out_path = _page_output_path(output_dir, page)
        previous_hashes = parse_page_hashes(out_path) if out_path.exists() else {}
        out_path.parent.mkdir(parents=True, exist_ok=True)
        out_path.write_text(render_page(page, priority, previous_hashes), encoding="utf-8")
        written.append(out_path)

    (output_dir / "INDEX.md").write_text(render_index(pages), encoding="utf-8")
    written.append(output_dir / "INDEX.md")
    return written
